### PR TITLE
Do not require steps to be pre-parsed

### LINKED ISSUE #166: logger called with wrong parameters
In Joyride.jsx#parseSteps this.logger is called with a string as the second argument instead of a list. That string gets "applied" to the logger function resulting in:

`Uncaught TypeError: CreateListFromArrayLike called on non-object`

Problem line:
`this.logger('joyride:parseSteps', 'Target not rendered. For best results only add steps after they are mounted.', s);`

Fix:
`this.logger('joyride:parseSteps', ['Target not rendered. For best results only add steps after they are mounted.', s]);`

### PR DESCRIPTION
**Pull request by IanVS**
Closes issue #155 & fixes #166 

## Description

In working towards the goal of not requiring the use of instance methods like `refs.joyride.parseSteps()`, this allows a "raw" set of steps to be provided directly to `Joyride` as props.  Joyride will then internally check that the steps are valid (they are the right type, have required fields, etc.).  

Instead of mutating the steps objects, a set of helper methods were broken out of the original `parseSteps` method, which can then be called at the points where they are needed.  This also means that DOM elements are not looked for on all steps right away (see caveats below for more on this).

Because we are no longer mutating the steps object, the adjusted properties are provided to `Tooltip` directly as props.  This seems to be a cleaner solution in any case, and I'd like to eventually avoid passing the `step` to the `Tooltip` and `Beacon` at all, giving it only the information it needs to render itself.  But that's for another day.

## Breaking Changes

I do not believe this introduces any breaking changes.  The `joyride.parseSteps` method will still function, but all it does now is log a deprecation warning and pass the provided steps straight back out.  At the next major version, the method could be removed entirely.

## Caveats
As I mentioned above, this no longer checks for a rendered DOM element for every step immediately upon mount.  I can't see any reason why this was necessary, as the DOM target only needs to exist when the Tooltip tries to render.  Maybe you can explain the reasoning why they were all checked up-front, it would be easy to add back in.  In my use case, though, it just adds a lot of noise to the console.

This PR has a lot of changes, but I tried to make reasonable, understandable commits.  When you are reviewing, I'd suggest that you step through commit-by-commit.  The main noise you will see when doing this is that I originally changed the `parseSteps` function to be `parseStep`, then removed it altogether, then remembered that I shouldn't make breaking changes and added it back in.  Other than that, the commits are pretty linear.  

Let me know if you have questions.  I hope this can be merged fairly soon, because I am making other changes and will begin to have merge conflicts with my other PRs.  In fact, this PR is not compatible with #158, so if you decide to merge one, do not merge the other right away before I have a chance to update it.  I'd recommend merging #158 before this one.

### CODE REVIEW

File: src/scripts/Joyride.jsx [hunk 1]
```diff
@@ -97,6 +103,12 @@ class Joyride extends React.Component {
     type: 'single'
   };
 
+  componentWillMount() {
```
Comment (IanVS) [inline src/scripts/Joyride.jsx]: I've realized this is the wrong lifecycle hook, because it's possible the rest of the DOM is not mounted either, so there won't be targets.  I'll be pushing a change shortly.

**Comment by IanVS** [comment]
Rebased, and ready for review, @gilbarbara.

Thanks!
